#!/bin/bash
# Download all 8 real images for B站视频
# Sources: Pexels (free stock photos)
OUTPUT_DIR="/Users/shizhangbin/Desktop/ascend-pipeline/episodes/第2期_昇腾部署Qwen3-VL-8B概念讲解/05_图片素材/real"

# Image 1: P02_s02 - Orange cat on windowsill
echo "Downloading [1/8] 橘猫趴在窗台上 (P02)..."
curl -sL "https://images.pexels.com/photos/15603440/pexels-photo-15603440.jpeg?auto=compress&cs=tinysrgb&w=1920" -o "$OUTPUT_DIR/real_P02_s02.jpg"
echo "  -> $(du -h "$OUTPUT_DIR/real_P02_s02.jpg" | cut -f1)"

# Image 2: P03_s03 - Handwritten messy note/menu
echo "Downloading [2/8] 手写潦草菜单/便签 (P03)..."
curl -sL "https://images.pexels.com/photos/7413838/pexels-photo-7413838.jpeg?auto=compress&cs=tinysrgb&w=1920" -o "$OUTPUT_DIR/real_P03_s03.jpg"
echo "  -> $(du -h "$OUTPUT_DIR/real_P03_s03.jpg" | cut -f1)"

# Image 3: P03_s03_2 - Hand-drawn wireframe sketch
echo "Downloading [3/8] 手绘网页布局草图 (P03)..."
curl -sL "https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=1920" -o "$OUTPUT_DIR/real_P03_s03_2.jpg"
echo "  -> $(du -h "$OUTPUT_DIR/real_P03_s03_2.jpg" | cut -f1)"

# Image 4: P06_s06 - Terminal screenshot (npu-smi info) - to be generated by Python
echo "Skipping [4/8] for Python generation..."

# Image 5: P21_s21 - Terminal screenshot (curl JSON response) - to be generated by Python  
echo "Skipping [5/8] for Python generation..."

# Image 6: P22_s22 - City street view
echo "Downloading [6/8] 城市街景 (P22)..."
curl -sL "https://images.pexels.com/photos/19242065/pexels-photo-19242065.jpeg?auto=compress&cs=tinysrgb&w=1920" -o "$OUTPUT_DIR/real_P22_s22.jpg"
echo "  -> $(du -h "$OUTPUT_DIR/real_P22_s22.jpg" | cut -f1)"

# Image 7: P23_s23 - Handwritten messy note (different)
echo "Downloading [7/8] 手写潦草便签 (P23)..."
curl -sL "https://images.pexels.com/photos/14992173/pexels-photo-14992173.jpeg?auto=compress&cs=tinysrgb&w=1920" -o "$OUTPUT_DIR/real_P23_s23.jpg"
echo "  -> $(du -h "$OUTPUT_DIR/real_P23_s23.jpg" | cut -f1)"

# Image 8: P24_s24 - Hand-drawn wireframe (different angle)
echo "Downloading [8/8] 手绘网页布局草图不同角度 (P24)..."
curl -sL "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=1920" -o "$OUTPUT_DIR/real_P24_s24.jpg"
echo "  -> $(du -h "$OUTPUT_DIR/real_P24_s24.jpg" | cut -f1)"

echo ""
echo "=== Download complete! ==="
ls -lh "$OUTPUT_DIR"/
